language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
  chrome: stable
dist: xenial
before_install:
- yes | gem update --system --force
- gem install bundler
script:
- yarn
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  YOUTUBE_API_KEY:
    secure: vke43Z8l+gkBpr3VZm+IfK3ohTkyk0It6MQNBbZBpmVGEPkDsMONSPplyJGwQ1uI7H65soxbfcBAQ1q6Bpc45rtINe/PpktagjxcMhi9WEe4y1HwWGwwHOMnxsQtnqKjrE9IL2U+nIoDRpkWqvjoBi/vwlGVb5Tn+r6iRVZCJ/FEURnOTwh21+JbnaoUgdDMyt6F1Cui3YbS/sPzojt8+UMDoxuZGxpnXPhQt6DEcSiCgUtoH2+/Vh8MmodnJcxVUMU4biPsWFiqKWpK6oRW2sVdto2Pncf9uEMBHh8k3jDUbVF7+s1X6KJmGcTFyCXw9sHzCeiLjgft1oXtGivxkNGNaOTlVeItR/t5nEbd2GnWX4bQSckwNFZWC7DjSwEoUHwyYm+k2VcAu0kea/BBIbOoi/Cmk5u4fFJlXLR66FNlyubr42P+PigK5N5tNjBTNcXbf3KYR++EYPta2iEVwLEWui9oSf4CDTSHW0p4aYXlawGVumIJyQmLP1903EN0Do/iGdeKXftdRQGWV7XcZ9Wcf19itf29lu3gIyNv9pxblbdmbojZZ90N8koyzXd79powA5RxW6+Ef612Ojcw4ujX4Ol5FlZGaALAC89QKy0gYCTc8k3izG+KWmp4xvT1ZdBAjHSRls6xKIHkZZzoxKxXggzEo9aXG7/xyKu3UTY=
  app: jt-jg-brownfield-of-dreams
  run: rails db:migrate
env:
  global:
    secure: 3B6kvcrY0DB5cvS3VrJgPsGPhx1G2AfPI3pm/gZuLCnROtBZzbESVryeSzuEeNZRG5WIg5b1W1XWqPl1LbFiuvDKf83g1Wh2drWRI8HtdbzuEzxxB0/00Uqk8D1gAiuoqk7GOj9WAT+SDtCZGmjED+MyzUh1nrFWJF02sDuo/owtHyrJQrULYHdrMsR2azGCZiDKU/AiSIEQ6+g5uJW/+QLGnZ8hma4VeTQne4I78lzG1DU6cO52uO2yEuURq/AGe4FHLuNNxEu0QOuQIbd8VyPLprZhUEyFV9v8GJ1pU5nlQOpyinchCIybxknzDj1NUFsBoZYeiBYUYNILjl0rlTcvi/z8vZDGW1iXs4sTB1IkSut5xZpYdyaiFORkrGRl/oPoPIiy6gNKpwtBog3cZ6Z4RsEd2xLOxr57+C/EzcwW+uxVsQf3+Nh/CQGumW3RPDlh8n1mfZs3rbRYmH2ipHexHuc7I4HzKm2EC+dxcuuyTuOvO9CrjmmB2c1UUhJ5ZUD2McYGWL+80X2AJ3xxaGHX+MtnKvuXircYzoIeuXI6mKGuXGT1qu3YaKvhqNkrflLHDkO+TkxFFFHdqc9FUEmb+DsBr8orTRWMp9zWULHyPhixJ5Oj4j13/vhe6mMJaNocv0m/Gb07CsDx2U5UPc8o5z1pfyMxTgKspFfxrqY=
