language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
  chrome: stable
dist: Bionic
before_install:
  - yes | gem update --system --force
  - gem install bundler
script:
- yarn
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
  secure: "c38Se32hx5NfNfx//eEjEp7K1SXY7OB2UzDT7DACCScR74eKzQ2iDlFrD06i9eflErz3lcFeCEETGXr9lo/zao2B5pd4TIIcxAAk4MkK0xflcQg6stfN4a6SKeI+uBdxs6BL3KO81jbOQ//ojvNiw/lzHcAvo/p7PVd94FXv8T9Qe1acgP/oBhNtvCkhvdeg+gNRz/bhz598qV6y4zxNKqHJ8ASjA3vZOJycM80amdLpYqbW7ZPs0aN6IL9kF3/jIOdqWh1RNtgrTErPdmcEED9PO9wQeOkYmCjZSs5RBnPh+6PPP/lFJCoMeKMf/nWVZD3zX8gD7DFVmorVdJViK3BQqxIOE4VIBqFEbCqRPu0EiVsw0qqRcwgTNN6S5kciPm9tLLF4NWfUX6FHgSnUjaIlNtnv/01XZWPhxN3PDyRJXB+br/KFhd/dl1+jtkJ+19i7YHpnWQSaMbvcFI576ZALpvnVtvsMKgXfn5idncZrbW5iGy13dw5PaP34rUQtuSwyKiidpMveBMZ7p0dlc7vVoKRcWiB35PBVMZqN81+Bme2K5KRXhAemA7QaRUJH3MtFx25/r9A6GacHG10zjp94+qnByiue9Ey0sqHFZAEALix3k9yICPFyZg8ksgeQNvH0Ip9hXvre4u8Pj6g87JqCp3YY8R5af5ezF8P/ic0=" 
  app: jt-jg-brownfield-of-dreams
  run: rails db:migrate db:seed
